name: StickerBasketball

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: gradle build -x test

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: StickerBasketball
          path: build/libs


  send_telegram_massage:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: exe

      - name: Archive
        run: |
          7z a StickerBasketball.7z StickerBasketball

      - name: ls
        run: ls -la

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO}}
          token: ${{ secrets.TELEGRAM_TOKEN}}
          message: uploaded artifacts
          document: main.7z


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bot:latest

      - name: Deploy to Self-Hosted Agent
        run: |
          docker stop sticker-basketball-container || true
          docker rm sticker-basketball-container || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/bot:latest
          docker run -d --name sticker-basketball-container \
          -e "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" \
          -e "BOT_NAME=${{ secrets.BOT_NAME }}" \
          ${{ secrets.DOCKER_USERNAME }}/bot:latest